// 首页壁纸
export const Cover = [
  "/img/cover/1.webp", 
  "/img/cover/2.webp", 
  "/img/cover/3.webp", 
  "/img/cover/4.webp", 
  "/img/cover/5.webp", 
  "/img/cover/6.webp", 
  "/img/cover/7.webp", 
  "/img/cover/8.webp", 
  "/img/cover/9.webp", 
  "/img/cover/10.webp", 
  "/img/cover/11.webp", 
  "/img/cover/12.webp", 
  "/img/cover/13.webp", 
  "/img/cover/14.webp", 
  // "/img/bg/15.webp", 
  // "/img/bg/16.webp",
  // "/img/bg/17.webp",
  // "/img/bg/18.webp",
  // "/img/bg/19.webp",
];
