// 首页壁纸
export const Cover = [
  "https://img.onedayxyy.cn/images/TeekCover/1.webp", 
  "https://img.onedayxyy.cn/images/TeekCover/2.webp", 
  "https://img.onedayxyy.cn/images/TeekCover/3.webp", 
  "https://img.onedayxyy.cn/images/TeekCover/4.webp", 
  "https://img.onedayxyy.cn/images/TeekCover/5.webp", 
  "https://img.onedayxyy.cn/images/TeekCover/6.webp", 
  "https://img.onedayxyy.cn/images/TeekCover/7.webp", 
  "https://img.onedayxyy.cn/images/TeekCover/8.webp", 
  "https://img.onedayxyy.cn/images/TeekCover/9.webp", 
  "https://img.onedayxyy.cn/images/TeekCover/10.webp", 
  "https://img.onedayxyy.cn/images/TeekCover/11.webp", 
  "https://img.onedayxyy.cn/images/TeekCover/12.webp", 
  "https://img.onedayxyy.cn/images/TeekCover/13.webp", 
  "https://img.onedayxyy.cn/images/TeekCover/14.webp", 
  "https://img.onedayxyy.cn/images/TeekCover/15.webp", 
  "https://img.onedayxyy.cn/images/TeekCover/16.webp",
  "https://img.onedayxyy.cn/images/TeekCover/17.webp",
  "https://img.onedayxyy.cn/images/TeekCover/18.webp",
  "https://img.onedayxyy.cn/images/TeekCover/19.webp",
];
